CC=g++
CFLAGS=-std=c++11 -Wall -Wextra

SRC=main.cpp
ENGINE_DIR=../engine
LSYSTEM_DIR=../lsystem

CINCLUDE_FLAGS=-I$(ENGINE_DIR) -I$(LSYSTEM_DIR)

all: main

main:
	$(CC) $(CFLAGS) $(CINCLUDE_FLAGS) $(SRC) -c
